apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: echo-app
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      chart: ./charts/app-template
      version: '0.1.x'
      sourceRef:
        kind: GitRepository
        name: this-repo
        namespace: flux-system
      interval: 1m
  values:
    replicaCount: 2
    name: echo-app
    image:
      name: mendhak/http-https-echo
      tag: 30
    configuration:
    - name: HTTP_PORT
      value: "80"