apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nginx-app
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      chart: ./charts/app-template
      version: '0.1.x'
      sourceRef:
        kind: GitRepository
        name: this-repo
        namespace: flux-system
      interval: 1m
  valuesFrom:
    - kind: Secret
      name: nginx-app-values
  values:
    replicaCount: 2
    name: my-nginx-app
    image:
      name: nginx
      tag: 1.24.0
#    configuration:
#    - name: NGINX_PORT
#      value: "80"