apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: elk
  namespace: monitoring
spec:
  interval: 1h0m0s
  url: https://helm.elastic.co
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: eck-operator
  namespace: flux-system
spec:
  chart:
    spec:
      chart: elastic/eck-operator
      sourceRef:
        kind: HelmRepository
        name: elk
      version: ">=1.15.0-0"
  interval: 1h0m0s
  releaseName: eck-operator
  targetNamespace: flux-system